abp85/locally

Gemfile
Gemfile.lock
app/policies/application_policy.rb
config/environments/development.rb
config/environments/production.rb
config/initializers/geocoder.rb
config/puma.rb
config/storage.yml
db/migrate/20200623084001_create_active_storage_tables.active_storage.rb
db/schema.rb

Added:
- ActiveStorage
- Cloudinary
- Pundit
- Geocoder
-Mapbox

Initial Setup

---

db/migrate/20200623100248_add_full_name_to_users.rb
db/schema.rb

Added first name and last name to User model

---

app/models/report.rb
db/migrate/20200623100847_create_reports.rb
db/schema.rb
test/models/report_test.rb

Added report model

---

app/models/report.rb
app/models/user.rb
app/models/vote.rb
db/migrate/20200623102147_create_votes.rb
db/schema.rb
test/models/vote_test.rb

Added vote model

---

app/assets/stylesheets/config/_colors.scss
app/assets/stylesheets/config/_fonts.scss

fonts and colors settled

---

app/models/category.rb
app/models/report.rb
db/migrate/20200623100847_create_reports.rb
db/migrate/20200623103045_create_categories.rb
db/schema.rb
test/models/category_test.rb

Added category model and fixed the report relationship

Added category model

---

app/controllers/application_controller.rb

Adding first and last name in the strong params for user

User attributes

---

app/models/report.rb
app/models/user.rb

Models validations

---

app/models/report.rb
db/migrate/20200623134224_add_status_to_reports.rb
db/schema.rb

Status column

---

app/views/devise/registrations/new.html.erb

Added first and last name to the user sign up form

Sign up form

---

app/controllers/reports_controller.rb

Skip action to Report show and index views

Devise Skip Action

---

app/controllers/reports_controller.rb
app/views/reports/index.html.erb

Index page

---

app/assets/stylesheets/components/_pill-category.scss
app/assets/stylesheets/pages/_report-show.scss
app/assets/stylesheets/toolbox/_text.scss
app/views/reports/index.html.erb
app/views/reports/show.html.erb

Implemented changes in the show

Reports show layout

---

app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_profile.scss
app/views/pages/profile.html.erb
app/views/reports/index.html.erb

hey guys, i worked on the profile page. However, it is not yet complete.

Profile front

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_search-bar.scss
app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_new.scss
app/views/reports/new.html.erb

Upload photo button modified
Copy of the form

Form modifications

---

app/controllers/reports_controller.rb
app/javascript/controllers/hello_controller.js
app/javascript/controllers/index.js
app/javascript/controllers/votes_controller.js
app/javascript/packs/application.js
app/views/reports/index.html.erb
app/views/reports/show.html.erb
package.json
yarn.lock

Added Ajax to the voting system

Ajax votes

---

app/assets/stylesheets/components/_btn-primary.scss
app/assets/stylesheets/components/_btn-secondary.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_search-bar.scss
app/assets/stylesheets/pages/_new.scss
app/views/pages/home.html.erb
app/views/reports/index.html.erb

Search bar design implemented
Fonts of buttons bigger

Search bar

---

app/assets/stylesheets/components/_btn-primary.scss
app/assets/stylesheets/components/_btn-secondary.scss
app/assets/stylesheets/pages/_new.scss
app/assets/stylesheets/pages/_profile.scss
app/views/reports/index.html.erb
app/views/reports/show.html.erb

Time ago implemented for show and modified in the cards of the index

time ago implemented for show and modified for index

---

app/views/pages/profile.html.erb
app/views/reports/index.html.erb

- index fixed while merging
- profile tabs added

Profile tabs

---

app/assets/stylesheets/pages/_profile.scss
app/views/pages/profile.html.erb

_profile.css
changed the .initials values for better positioning of user's initials

profile initials positioning

---

app/assets/stylesheets/components/_bottom-navbar.scss
app/assets/stylesheets/components/_profile-card.scss
app/assets/stylesheets/components/_report-card.scss
app/assets/stylesheets/pages/_home.scss
app/assets/stylesheets/pages/_reports-index.scss
app/helpers/meta_tags_helper.rb
app/views/pages/home.html.erb
app/views/pages/profile.html.erb
app/views/reports/index.html.erb
config/initializers/default_meta.rb
config/meta.yml

Creating meta tags
Bottom navbar plus centered
Implementing pluralize for the votes. Done in HTML Not finished CSS yet

Frontend fixes
